openapi: 3.0.0
info:
  title: Todoapp
  description: Todoapp web api
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local Development Web API
paths:
  /users/me:
    get:
      security:
        - bearerAuth: []
      summary: Returns the current user
      description: 
      responses:
        '200':    # status code
          description: a JSON array of user info
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /auth/signin:
    post:
      summary: Returns user info and token
      description: User Login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserForm'
      responses:
        '201':
          description: A json array of user and token
  /auth/signup:
    post:
      summary: Returns user info and token
      description: signup user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: A json array of user and token
          content:
components:
  schemas:
    UserForm:
      type: object
      properties:
        name:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
